--KASKADOWA AKTUALIZACJA

CREATE TABLE FABRYKA(
	ID INT PRIMARY KEY);

CREATE TABLE PRODUKT(
	NAZWA CHAR(25) PRIMARY KEY,
	ILOSC DECIMAL(6,3), --w kilogramach
	CENA MONEY,			--za kilogram
	ID_FABRYKI INT REFERENCES FABRYKA ON DELETE CASCADE ON UPDATE CASCADE); 

INSERT INTO FABRYKA
	VALUES	(1),
			(2)

INSERT INTO PRODUKT
VALUES	('twaróg', 45.436, 16.03, 1),
		('ser zóty', 500, 20, 1),
		('gruszki', 50.7, 6.6, 2)

SELECT * FROM PRODUKT
SELECT * FROM FABRYKA

UPDATE FABRYKA SET ID = 3 WHERE ID = 1

SELECT * FROM PRODUKT
SELECT * FROM FABRYKA

DROP TABLE PRODUKT
DROP TABLE FABRYKA 