--KASKADOWE USUWANIE

CREATE TABLE FABRYKA(
	ID INT IDENTITY PRIMARY KEY,
	NAZWA CHAR(50));

CREATE TABLE PRODUKT(
	NAZWA CHAR(25) CHECK(LEN(NAZWA)>=3) PRIMARY KEY,
	ILOSC DECIMAL(6,3), --w kilogramach
	CENA MONEY,			--za kilogram
	ID_FABRYKI INT REFERENCES FABRYKA ON DELETE CASCADE); 

INSERT INTO FABRYKA
	VALUES	('MLECZARNIA'),
			('HURTOWNIA_OWOC�W')

INSERT INTO PRODUKT
VALUES	('twar�g', 45.436, 16.03, (SELECT ID FROM FABRYKA WHERE NAZWA = 'MLECZARNIA')),
		('ser ��ty', 500, 20, (SELECT ID FROM FABRYKA WHERE NAZWA = 'MLECZARNIA')),
		('gruszki', 50.7, 6.6, (SELECT ID FROM FABRYKA WHERE NAZWA = 'HURTOWNIA_OWOC�W'))

SELECT * FROM PRODUKT
SELECT * FROM FABRYKA

DELETE FROM FABRYKA WHERE NAZWA = 'MLECZARNIA'

SELECT * FROM PRODUKT
SELECT * FROM FABRYKA

DROP TABLE PRODUKT
DROP TABLE FABRYKA 